export const ingredients = [
    // Vegetables
    'Carrot',
    'Broccoli',
    'Spinach',
    'Tomato',
    'Cucumber',
    'Bell Pepper',
    'Onion',
    'Garlic',
    'Potato',
    'Zucchini',
    'Cauliflower',
    'Green Beans',
    'Mushroom',
    'Celery',
    'Lettuce',
    'Beetroot',
    'Radish',
    'Eggplant',
    'Sweet Potato',
    'Asparagus',
  
    // Kitchen Ingredients
    'Salt',
    'Pepper',
    'Olive Oil',
    'Butter',
    'Garlic Powder',
    'Onion Powder',
    'Paprika',
    'Cumin',
    'Turmeric',
    'Chili Powder',
    'Soy Sauce',
    'Vinegar',
    'Honey',
    'Soy Sauce',
    'Balsamic Vinegar',
    'Dried Herbs',
    'Lemon Juice',
    'Soy Sauce',
    'Mustard',
    'Sugar',
    'Flour',
    'Baking Powder',
    'Yeast',
    'Milk',
    'Cream',
    'Cheese',
    'Eggs'
  ];
  